version: '3.4'

services:
  reactclient.ui:
    container_name: react-client-ui
    image: reactclientui
    build:
      context: ./..
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
