module.exports={
    SignIn:"/Authorization/Authorize",
    SignUp:"/Users/CreateUser",
    UpdatePassword:"/Users/UpdatePassword",
    ResetPassword:"/Users/ResetPassword",
    RefreshToken:"/Authorization/RefreshToken",    
    GetUser:"/Users/GetUser",
    GetUserByEmail:"/Users/GetUserByEmail",
    UpdateUser:"/Users/UpdateUser",
    DeleteUser:"Users/DeleteUser",
    //Catalog
    GetCategories:"/categories/getcategories",
    GetWorkspaciesPaged:"/Workspacies/GetWorkspaciesPaged"
}