module.exports={
    SignIn:"/Authorization/Authorize",
    SignUp:"/Users/CreateUser",
    UpdatePassword:"/Users/UpdatePassword",
    ResetPassword:"/Users/ResetPassword",
    RefreshToken:"/Authorization/RefreshToken",    
    GetUser:"/Users/GetUser",
    GetUserByEmail:"/Users/GetUserByEmail",
    UpdateUser:"/Users/UpdateUser",
    DeleteUser:"/Users/DeleteUser",
    //Catalog
    GetCategories:"/categories/getcategories",
    UpdateCategory:"/categories/updatecategory",
    GetWorkspaciesPaged:"/Workspacies/GetWorkspaciesPaged",
    GetWorkspace:"/Workspacies/GetWorkspaces",
    CreateWorkspace:"/workspacies/createworkspace",
    UpdateWorkspace:"/workspacies/updateworkspace",
    DeleteWorkspace:"/workspacies/deleteworkspace",
    //Booking
    CreateBooking:"/Bookings/CreateBooking",
    UpdateBooking:"/Bookings/UpdateBooking",
    DeleteBooking:"/Bookings/DeleteBooking",
    GetBookingsByWorkspace:"/Bookings/GetBookingsByWorkspace",
    GetBookingsByUser:"/Bookings/GetBookingsByUser"
}