version: '2.1'

services:
  ocelotapigateway:
    container_name: ocelot-api-gateway
    image: ${DOCKER_REGISTRY-}ocelotapigateway
    build:
      context: ./..
      dockerfile: ./src/ApiGateway.Api/Dockerfile
