# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '2.1'

services:
  mssql-server:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
        ACCEPT_EULA: "Y"
        SA_PASSWORD: "QQQzzz_7584424"
        MSSQL_PID: "Express"
    ports:
        - "1433:1433" 
  catalogservice.api:
    container_name: catalogserviceapi
    build:
      context: ./..
      dockerfile: ./src/CatalogService.Api/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT : "Development"
      DatabaseServer: "mssql-server"
      DatabasePort: "1433"
      DatabaseUser: "sa"
      DatabasePassword: "QQQzzz_7584424"
      DatabaseName: "workspaceCatalog"  
      RabbitMQHost: "rabbitmq"
      RabbitMQPort: "5672"
      RabbitMQUser: "user"
      RabbitMQPassword: "mypass"
    ports:
      - "8000:80"
      - "8001:443"
    depends_on:    
        mssql-server:
            condition: service_started
        rabbitmq:
          condition: service_healthy    
  rabbitmq:
    build: rabbitmq/.
    hostname: rabbitmq
    container_name: rabbitmq
    environment:
        - RABBITMQ_DEFAULT_USER=user
        - RABBITMQ_DEFAULT_PASS=mypass
        - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit disk_free_limit 2147483648
    ports:
        # RabbitMQ instance
        - "5672:5672"
        # Web interface
        - "15672:15672"
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:15672"]
        interval: 5s
        timeout: 15s
        retries: 3
