# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq
    hostname: rabbitmq
  mssql-server:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
        ACCEPT_EULA: "Y"
        SA_PASSWORD: "QQQzzz_7584424"
        MSSQL_PID: "Express"
    ports:
        - "1433:1433" 
  catalogservice.api:
    container_name: catalogserviceapi
    build:
      context: ./..
      dockerfile: ./src/CatalogService.Api/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT : "Development"
      DatabaseServer: "mssql-server"
      DatabasePort: "1433"
      DatabaseUser: "sa"
      DatabasePassword: "QQQzzz_7584424"
      DatabaseName: "workspaceCatalog"  
    ports:
      - "8000:80"
      - "8001:443"

volumes: 
  rabbitmqdata:
  