# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    hostname: rabbitmq
    container_name: rabbitmq
    restart: always
    environment:
        - RABBITMQ_DEFAULT_USER=user
        - RABBITMQ_DEFAULT_PASS=mypass
        - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit disk_free_limit 2147483648
    healthcheck:
        test: rabbitmq-diagnostics -q ping
        interval: 5s
        timeout: 15s
        retries: 3
    networks:
        - services-network
    ports:
        # RabbitMQ instance
        - "5672:5672"
        # Web interface
        - "15672:15672"
    volumes:
        - rabbitmqdata:/var/lib/rabbitmq
  mssql-server:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
        ACCEPT_EULA: "Y"
        SA_PASSWORD: "QQQzzz_7584424"
        MSSQL_PID: "Express"
    networks:
      - services-network
    ports:
        - "1433:1433" 
  bookingservice.api:
    container_name:  bookingserviceapi
    build:
      context: ./..
      dockerfile: ./src/BookingService.Api/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DatabaseServer: "mssql-server"
      DatabasePort: "1433"
      DatabaseUser: "sa"
      DatabasePassword: "QQQzzz_7584424"
      DatabaseName: "workspaceBooking"
      RabbitMQHost: "rabbitmq"
      RabbitMQPort: "5672"
      RabbitMQUser: "user"
      RabbitMQPassword: "mypass"
    ports:
      - "7000:80"
      - "7001:443"
    networks:
      - services-network
    depends_on:
        rabbitmq:
          condition: service_healthy

volumes: 
  rabbitmqdata:

networks:
  services-network: